name: Run Tests

on: [push]
jobs:
  RunEndToEndTests:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag arcticstorm9/flightowl-api
    - name: Run server
      run: docker run arcticstorm9/flightowl-api -p 8000:8000
    - name: Install Dependencies
      run: pip install -r tests/requirements.txt
    - name: Run pytest
      run: pytest --color=yes tests/test_users_route.py
